# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# The target name is most likely the name of your project.

target 'NumberTileGame' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NumberTileGame

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other susspecs you want to use in your project
  ]

  target 'NumberTileGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
